
PLAYER1 = "PLAYER1"
PLAYER2 = "PLAYER2"
PLAYER1_SYMBOL = "X"
PLAYER2_SYMBOL = "O"
EMPTY_SYMBOL = ""
PLAYER1_COLOR = "Blue"
PLAYER2_COLOR = "Red"
GAME_STATE_INACTIVE = "inactive"
GAME_STATE_OVER = "over"
GAME_STATE_ACTIVE = "active"
GAME_RESULT_DRAW = "draw"
GAME_RESULT_WIN_PLAYER1 = "PLAYER1 win"
GAME_RESULT_WIN_PLAYER2 = "PLAYER2 win"

ROWS = 3
COLS = 3
